on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # macOS targets
          - goarch: amd64
            goos: darwin
          - goarch: arm64
            goos: darwin
          # Linux targets
          - goarch: "386"
            goos: linux
          - goarch: amd64
            goos: linux
          - goarch: arm
            goos: linux
          - goarch: arm64
            goos: linux
          - goarch: mips
            goos: linux
          - goarch: mipsle
            goos: linux
          - goarch: mips64
            goos: linux
          - goarch: mips64le
            goos: linux
          - goarch: loong64
            goos: linux
          - goarch: riscv64
            goos: linux
          # Windows targets
          - goarch: "386"
            goos: windows
          - goarch: amd64
            goos: windows
          - goarch: arm
            goos: windows
          - goarch: arm64
            goos: windows
    steps:
      - name: Show environment
        run: export
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          build_command: "make"
          build_flags: "release"
          binary_name: "parquet-tools"
          extra_files: parquet-tools
